# Projet - Apprentissage Profond - Implémentation (Partie Perceptron)

**EL KAAKOUR Ahmad & Matthieu RANDRIANTSOA**

> Ce notebook contient toutes les fonctions d'implémentation de la partie I. Il est conçu de sorte à s'exécuter sequentiellement.

In [ ]:
import gzip, numpy, torch
import matplotlib.pyplot as plt
from pathlib import Path
import itertools
import json
import os
import pandas as pd
import seaborn as sns

## Définition des hyperparamètres

In [ ]:
batch_size = 5 # nombre de données lues à chaque fois
nb_epochs = 10 # nombre de fois que la base de données sera lue
eta = 0.00001 # taux d'apprentissage
w_min = -0.001
w_max = 0.001

## Chargement des données

In [ ]:
((data_train,label_train),(data_test,label_test)) = torch.load(gzip.open('data/mnist.pkl.gz'), weights_only=False)

## Analyse des dimensions des données importées

In [ ]:
print(f"data_train shape: {data_train.shape}")
print(f"label_train shape: {label_train.shape}")
print(f"data_test shape: {data_test.shape}")
print(f"label_test shape: {label_test.shape}")

data_train shape: torch.Size([63000, 784])
label_train shape: torch.Size([63000, 10])
data_test shape: torch.Size([7000, 784])
label_test shape: torch.Size([7000, 10])


## Préparation des données

In [ ]:
training_dataset = torch.utils.data.TensorDataset(data_train, label_train)
test_dataset = torch.utils.data.TensorDataset(data_test, label_test)

training_loader = torch.utils.data.DataLoader(training_dataset, batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=1, shuffle=True)

## Définition du modèle

### Choix du type de modèle

In [ ]:
model = torch.nn.Linear(data_train.shape[1], label_train.shape[1]) # Création d'un neurone avec fonction d'activation linéaire
torch.nn.init.uniform_(model.weight,w_min,w_max) # Initialisation des poids

Parameter containing:
tensor([[-3.7899e-04,  7.6127e-04, -8.7735e-04,  ...,  8.0522e-04,
         -8.7891e-04, -1.3761e-04],
        [ 5.8214e-04, -8.9656e-04, -2.2406e-04,  ..., -3.2075e-04,
         -6.6475e-04, -4.3368e-07],
        [-5.2841e-04,  2.2538e-05,  2.0944e-04,  ..., -7.9608e-04,
         -1.2805e-04,  7.8641e-04],
        ...,
        [ 9.6606e-04, -6.3284e-04, -9.0118e-04,  ...,  2.0879e-04,
          9.0254e-04, -3.6840e-04],
        [ 3.6540e-04,  4.0142e-04,  5.1121e-04,  ...,  6.7428e-05,
          6.7835e-05, -9.9374e-04],
        [-7.0315e-04,  3.0334e-04,  7.4311e-05,  ...,  5.7517e-04,
          3.4898e-05, -2.0953e-04]], requires_grad=True)

### Définition de la fonction côut et d'optimisation

In [ ]:
loss_func = torch.nn.MSELoss(reduction='sum')
optim = torch.optim.SGD(model.parameters(), lr = eta)

## Apprentissage & Tests

In [ ]:
test_loss_values = []
for n in range(nb_epochs):
    for x,t in training_loader:

        y = model(x)

        loss = loss_func(y, t) # Compare les prédictions y aux vraies valeurs t
        loss.backward() # Calcul le gradient de la perte par rapport aux paramètres du modèles
        optim.step() #
        optim.zero_grad()

    model.eval()

    with torch.no_grad():

        acc = 0.
        # on lit toutes les donnéees de test
        for x,t in test_loader:
          # on calcule la sortie du modèle
          y = model(x)
          # on regarde si la sortie est correcte
          acc += torch.argmax(y,1) == torch.argmax(t,1)
        # on affiche le pourcentage de bonnes réponses
        print(acc/data_test.shape[0])


tensor([0.8254])
tensor([0.8419])
tensor([0.8474])
tensor([0.8529])
tensor([0.8537])
tensor([0.8551])
tensor([0.8547])
tensor([0.8556])
tensor([0.8546])
tensor([0.8573])


## Test final

In [ ]:
acc = 0.
# on lit toutes les donnéees de test
for x,t in test_loader:
  # on calcule la sortie du modèle
  y = model(x)
  # on regarde si la sortie est correcte
  acc += torch.argmax(y,1) == torch.argmax(t,1)
# on affiche le pourcentage de bonnes réponses
print(acc/data_test.shape[0])

tensor([0.8573])
